version: '3.7'
services:
  flaskapp:
    container_name: flaskapp
    build: .
    env_file:
      - .env
    volumes:
      - './:/app'
    ports:
      - 5001:5000
    networks:
      - sh-network
      - nginx-proxy_default
    depends_on:
      - neo4j

  neo4j:
    container_name: 'neo4j'
    image: neo4j:4.4.15-enterprise
    env_file:
      - .env
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j-data:/data
    networks:
      - sh-network
  
networks:
  sh-network:
    external: false
    name: sh-network
  nginx-proxy_default:
    external: true 
